# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0840fd4038487d1afc5c40c69023d363ebc2390209e5d9e1588e634bb214c2de0c1869e54bd8cc6ddae0d84da8fda5bec66a0a55fdf483b5b1743bfe0688d74a

test:
  secret_key_base: 4ed9712da3f2f3b5e2b5f859b1e6a52415fc8faf948a0e803a6796ae519f1a32f238229ad23b3b840115a68fb03aabbc4be8fcd48318134e6a0e346c21726584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
